python train.py -s ../../../3DGS-DR/data/GlossyReal/maneki -m output/GlossyReal_material_sam/maneki1 --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000 --num_emitters 2 #--lambda_emit_sparsity 0.1 #--lambda_emit_gate_cons 0.1 --lambda_emit_residual 0.1
python train.py -s ../../../3DGS-DR/data/GlossyReal/bunny -m output/GlossyReal_material_sam/bunny --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000 --num_emitters 2  #--lambda_emit_sparsity 0.1 #--lambda_emit_gate_cons 0.1 --lambda_emit_residual 0.1
python train.py -s ../../../3DGS-DR/data/GlossyReal/bear -m output/GlossyReal_material_sam/bear --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000 --num_emitters 2 #--lambda_emit_sparsity 0.1 #--lambda_emit_gate_cons 0.1 --lambda_emit_residual 0.1
python train.py -s ../../../3DGS-DR/data/GlossyReal/vase -m output/GlossyReal_material_sam/vase --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000 --num_emitters 2  #--lambda_emit_sparsity 0.1 #--lambda_emit_gate_cons 0.1 --lambda_emit_residual 0.1
python train.py -s ../../../3DGS-DR/data/GlossyReal/coral -m output/GlossyReal_material_sam/coral --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000 --num_emitters 2  #--lambda_emit_sparsity 0.1 #--lambda_emit_gate_cons 0.1 --lambda_emit_residual 0.1

#python train.py -s ../../../3DGS-DR/data/GlossyReal/bear -m output/GlossyReal_material_test3/bear --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000  #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
#Python train.py -s ../../../3DGS-DR/data/GlossyReal/bunny -m output/GlossyReal_material_test3/bunny --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000  #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
#python train.py -s ../../../3DGS-DR/data/GlossyReal/vase -m output/GlossyReal_material_test3/vase --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000  #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
#python train.py -s ../../../3DGS-DR/data/GlossyReal/coral -m output/GlossyReal_material_test3/coral --eval --iterations 30000 --initial 1 --init_until_iter 3000  -r 1 --emitters_from_iter 3000  #--lambda_hybrid 0.1 --uncertainty_lr 0.001 --uncertainty_from_iter 10000
